name: authorisation
description: Authorisation package with landing page.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  hooks_riverpod: ^2.1.1
  pocketbase: ^0.5.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
